name: Attach build artifacts to release


inputs:
  filename:
    description : 'Filename of the build artifact'
    required    : true
  upload_url:
    description : 'Upload URL of the release'
    required    : true
  GITHUB_TOKEN:
    description : 'Secret GitHub token required for uploading to the release'
    required    : true


runs:
  using: composite
  steps:
  -
    name : Download artifacts
    uses : actions/download-artifact@v3
    with:
      name : ${{ inputs.filename }}
      path : ./out/
  -
    name : Attach .nro file to release
    uses : actions/upload-release-asset@v1
    env:
      GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    with:
      upload_url         : ${{ inputs.upload_url }}
      asset_path         : ./out/${{ inputs.filename }}.nro
      asset_name         : ${{ inputs.filename }}.nro
      asset_content_type : application/octet-stream
  -
    name : Attach .elf file to release
    uses : actions/upload-release-asset@v1
    env:
      GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    with:
      upload_url         : ${{ inputs.upload_url }}
      asset_path         : ./out/${{ inputs.filename }}.elf
      asset_name         : ${{ inputs.filename }}.elf
      asset_content_type : application/x-elf
